package controller;

import javafx.fxml.FXML;
import javafx.scene.Group;
import javafx.scene.control.Button;
import javafx.scene.input.MouseEvent;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.layout.AnchorPane;

import javafx.scene.shape.Circle;
import model.AbstractGames;
import model.AppRunningManager;

public class Game2Controller extends AbstractGames{
	@FXML
	private AnchorPane GamePane;
	@FXML
	private Button Game_pause_btn;
	@FXML
	private Button Game_exit_btn;
	@FXML
	private Button Game_skip_btn;
	@FXML
	private Circle Game_Target;
	@FXML
	private Button Game_how_btn;
	
	private int counter=0;
	private int score=0;
	private double x;
	private double y;
	
	public void initialize()
	{
		//Game_Target.setVisible(false);
		setType(AppRunningManager.getCurrentGame().getType());
		setDifficulty(AppRunningManager.getCurrentGame().getDifficulty());
		setRepetition("12");
		initializeEventHandler();
		randomCreateTargets();
		
	}
	
	public void initializeEventHandler()
	{
		EventHandler<MouseEvent> eventHandler=new EventHandler<MouseEvent>() {

			@Override
			public void handle(MouseEvent arg0) {
				// TODO Auto-generated method stub
				counter++;
				if ((arg0.getX()>=(x-50.0))&&(arg0.getX()<=(x+50.0))&&(arg0.getY()>=(y-50.0))&&(arg0.getY()<=(y+50.0))) {
					score++;
				}
				
				System.out.print("counter: "+counter+";");
				System.out.println("score: "+score+".");
				randomCreateTargets();
				if (counter>=12) {
					GamePane.removeEventHandler(MouseEvent.MOUSE_CLICKED, this);
					finish(score);
				}
			}
		};
		GamePane.addEventHandler(MouseEvent.MOUSE_CLICKED, eventHandler);
	}
	
	private void randomCreateTargets() {
		// TODO Auto-generated method stub
		x=Math.random()*800;
		Game_Target.setLayoutX(x);
		y=Math.random()*450;
		Game_Target.setLayoutY(y);
		Game_Target.setRadius(30.0);
		
		Group group=new Group();
		group.getChildren().add(Game_Target);
	
		GamePane.getChildren().addAll(group);
		
	}

	// Event Listener on Button[#Game_pause_btn].onAction
	@FXML
	public void ActionOnGame_pause_btn(ActionEvent event) {
		// TODO Autogenerated
		try {
			pause();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#Game_exit_btn].onAction
	@FXML
	public void ActionOnGame_exit_btn(ActionEvent event) {
		// TODO Autogenerated
		try {
			exitGame();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#Game_skip_btn].onAction
	@FXML
	public void ActionOnGame_skip_btn(ActionEvent event) throws Exception {
		// TODO Autogenerated
		skip();
	}
	@FXML
	public void ActionOnGame_how_btn(ActionEvent event) throws Exception{
		tutorial();
	}
	public void tutorial() throws Exception {
		AppRunningManager.loadScene("GameTutorial2", 800, 450);
	}
}
